services:

  nginx:
    build:
      context: './build/nginx'
      args:
        - NGINX_IMAGE=${NGINX_IMAGE:-nginx:1-alpine-slim}
    environment:
      - NGINX_WEB_ROOT=${NGINX_WEB_ROOT:-/var/www/html}
      - NGINX_HTTP_PORT=${NGINX_HTTP_PORT:-80}
      - NGINX_HTTPS_PORT=${NGINX_HTTPS_PORT:-443}
    networks:
      default:
        aliases:
          - php.web
    ports:
      - "${NGINX_EXPOSE_TO_IP:-127.0.0.1}:${NGINX_HTTP_PORT:-}:80"
      - "${NGINX_EXPOSE_TO_IP:-127.0.0.1}:${NGINX_HTTPS_PORT:-}:443"
    expose:
      - 80
      - 443
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - ${NGINX_VOLUME_SOURCE:-../public}:/var/www/html/public
      - ./build/nginx/certs:/etc/ssl/certs
      - ./logs/nginx:/var/log/nginx
