version: '3.7'
services:

  postgres:
    image: '${POSTGRES_IMAGE:-postgres:15-alpine}'
    environment:
      POSTGRES_USER: '${POSTGRES_USER:-root}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD:-password}'
    ports:
      - '127.0.0.1:${POSTGRES_EXPOSE_PORT:-}:5432'
    expose:
      - 5432
#    tmpfs:
#      - /var/lib/postgresql/data
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
      - ./build/postgres/profile.d:/etc/profile.d
