services:

  redis:
    image: '${REDIS_IMAGE:-redis:alpine}'
    expose:
      - 6379
    volumes:
      - ./volumes/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 5s
